### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by Jimbly** [boyers/socket.js#1]
> - ...drop messages (and not resend them) if there is a network partition.
> 
> That last point may be surprising to you. 

That does surprise me!  What does dropping messages have to do with partitioning?  Perhaps you meant "interruption" which is used a couple sentences later...

**Comment by stepchowfun** [comment]
Ah, yes—perhaps "network partition" was the wrong choice of words there. Messages are dropped any time the socket is closed (e.g., due to intermittent network issues). If the socket was closed due to a network failure (not because the client/server explicitly closed it), the client will try to reconnect (forever, until it succeeds). You're welcome to submit a pull request for copyediting. :smile:

**Comment by stepchowfun** [comment]
Addressed in https://github.com/boyers/socket.js/commit/4cf56d9f26b26ef80dee373be9bac6cad5936b5e.
